export const IPC = {
  INVOICE_LIST:           'invoice:list',
  INVOICE_GET:            'invoice:get',
  INVOICE_CREATE:         'invoice:create',
  INVOICE_UPDATE:         'invoice:update',
  INVOICE_DELETE:         'invoice:delete',
  INVOICE_LINK_PDF:       'invoice:linkPdf',
  INVOICE_OPEN_PDF:       'invoice:openPdf',
  DASHBOARD_STATS:        'dashboard:stats',
  IMPORT_START:           'import:start',
  IMPORT_PROGRESS:        'import:progress',
  SYNC_START:             'sync:start',
  SYNC_PROGRESS:          'sync:progress',
  SYNC_STATUS:            'sync:status',
  SETTINGS_GET:           'settings:get',
  SETTINGS_SAVE:          'settings:save',
  DIALOG_OPEN_FILE:       'dialog:openFile',
  DIALOG_OPEN_FOLDER:     'dialog:openFolder',
} as const;
